### ISSUE TITLE
sodium release

### ISSUE THREAD

**Issue by java-artisan** [USEF-Foundation/ri.usef.energy#1]
The test NaClTest fails for Linux. Which is a problem because it wants *exactly* Sodium 1.0.10. Which isn't available for Debian distributions. The latest Ubuntu derivates and Debian Stable all track Sodium 1.0.8. With which the build succeeded until the last commit.

Debian Stretch tracks Sodium 1.0.11. I can force a Jessy to use that package. But it's a hack and the test fails anyway - because it's not 1.0.10 either.

The only solution would be to build Sodium 1.0.10 from source. Which is absurd unless Usef RI really is unable to work with 1.0.8 or 1.0.11. 

If not, I advise to downgrade this requirement back to 1.0.8 since this is by large the most commonly used version for Debian- and Ubuntu releases. Or to define a range of usable Sodium versions.

**Comment by brouwee** [comment]
We will fix the issue in the upcoming release of the USEF Reference Implementation that is tentatively scheduled for the end of this month.

**Comment by brouwee** [comment]
The fix for this issue is included in today's release (1.3.6).
