### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by java-artisan** [USEF-Foundation/ri.usef.energy#2]
The documentation is not in sync with the software. It would help immensely the comprehension if mentioned screenshots, paths, ... were always referencing existing files; systems, ...

**Comment by MVolkerts** [comment]
Thank you for your observation. To address this issue, please be more specific about the sections of the documentation you feel need improvement and open a separate issue per documentation item. 

You are also invited to address these issues yourself and help our community to improve USEF!
