### ISSUE TITLE
Support for */xml content types

### ISSUE THREAD

**Issue by java-artisan** [USEF-Foundation/ri.usef.energy#3]
Sending (test) messages only succeeds using text/xml content type. However, the vast number of test tools will use application/xml. And next to that surely there are other variations. Presumably the only important about the content type is that it is xml.

**Comment by thgraaf** [comment]
We used SoapUI and Postman and with both testtools the content type can be adjusted in the header to text/xml. If you can tell me what testtool(s) you are using, I will try to help you adjust the content type.

**Comment by MVolkerts** [comment]
Closing the issue due to lack of response.
