### ISSUE TITLE
Unsafe Usef public key distribution

### ISSUE THREAD

**Issue by jan-goyvaerts-enervalis** [USEF-Foundation/ri.usef.energy#8]
Public keys are currently distributed by means of DNS entries on public DNS servers. 

The problem is that those DNS servers can easily be spoofed with today's tools. An attacker can easily set up a rogue DNS server with his own public key on it. Inducing the other participants in the false assumption they are conversing with a legit USEF participant.

That's the reason the original spec was based on DNSSEC - using a secured DNS server.

The current situation is good enough for testing. But for production this should be different.

**Comment by Milo9999** [comment]
Your statement about DNS/DNSSEC is true, but we think this is a deployment issue. DNSSEC cannot be part of the RI itself, therefore it cannot be solved in the RI. However, to be 100% USEF compliant, the use of DNSSEC is mandatory, making this less of an issue.
