### ISSUE TITLE
Use proven and provided encryption algorithm

### ISSUE THREAD

**Issue by jan-goyvaerts-enervalis** [USEF-Foundation/ri.usef.energy#9]
USEF is using NaCl to digitally sign the message data. Mind you, I'm not pretending this is an unsafe algorithm ! But rather that it's not proven to be safe. While there are loads of proven strong algorithms available out of the box, shipped with Java's JDK.

I presume NaCl has been chosen because it's fast compared to other algorithms. If this the reason, then its usage is unjustified. For Usef we're talking about low-volume traffic with lots of allowed latency.

Next to that USEF should use Java's SPI to use the encryption code, as it is meant to be. It allows fast switching between algorithms by not hard coding the encryption library api into the application's code.

**Comment by Milo9999** [comment]
NaCl/libsodium is prescribed by the USEF design. We will pass the suggestion to the design team.
